//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentNoteMvcProject.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTES
    {
        public int NOTEID { get; set; }
        public Nullable<byte> LECTUREID { get; set; }
        public Nullable<int> STUDENTID { get; set; }
        public Nullable<byte> FIRSTEXAM { get; set; }
        public Nullable<byte> SECONDEXAM { get; set; }
        public Nullable<byte> THIRDEXAM { get; set; }
        public Nullable<byte> PROJECT { get; set; }
        public Nullable<decimal> AVERAGE { get; set; }
        public Nullable<bool> SITUTATION { get; set; }
    
        public virtual LESSONS LESSONS { get; set; }
        public virtual STUDENTS STUDENTS { get; set; }
    }
}
