//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentNoteMvcProject.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENTS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STUDENTS()
        {
            this.NOTES = new HashSet<NOTES>();
        }
    
        public int STUDENTID { get; set; }
        public string STUDENTNAME { get; set; }
        public string STUDENTSURNAME { get; set; }
        public string STUDENTIMAGE { get; set; }
        public string STUDENTGENDER { get; set; }
        public Nullable<byte> STUDENTCLUB { get; set; }
    
        public virtual CLUBS CLUBS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NOTES> NOTES { get; set; }
    }
}
